FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml /app/
RUN pip install --no-cache-dir --upgrade pip setuptools wheel &&     pip install --no-cache-dir fastapi uvicorn[standard] gunicorn pydantic pydantic-settings sqlalchemy alembic redis celery python-json-logger prometheus-client ldap3 httpx grpcio protobuf structlog

COPY src /app/src
ENV PYTHONPATH=/app/src

COPY infra/gunicorn_conf.py /app/infra/gunicorn_conf.py
COPY monitoring/logging/logging.yaml /app/monitoring/logging/logging.yaml

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-c", "infra/gunicorn_conf.py", "app.main:app"]
